import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SocketProvider from "./context/SocketProvider";
import Navigation from "../components/Navigation/Navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      {/* <SocketProvider> */}
      <body className="w-screen h-screen overflow-hidden relative">
        {children}
      </body>
      {/* </SocketProvider> */}
    </html>
  );
}
